### ISSUE TITLE
Primary login mode with mixed authentication hides reset password form

### ISSUE THREAD

**Issue by sevapetrov** [clef/clef-wordpress#179]
**Issue**:

On WP installs with Clef available as a login option alongside the traditional password authentication, the form at `/wp-login.php?action=lostpassword` is overlaid by the white background normally used with the Clef bars.

**Description**:

More specifically, Clef sets `visibility: hidden` on each `input` and `label` child element of `form id="lostpasswordform"` as you can see in the following excerpt from `main.min.css`:

``` scss
66.  .clef-login-form.clef-login-form-embed:not(.clef-override-or-invite):not(.clef-auto-connect-account):not(.clef-show-username-password) #login input, .clef-login-form.clef-login-form-embed:not(.clef-override-or-invite):not(.clef-auto-connect-account):not(.clef-show-username-password) 
67.    #login label {    visibility: hidden;  }
```

I stopped here, figuring it's either only happening to me and, _purely hypothetically_, some other hosts one could potentially find through Google. It could very well be related to a setup problem with a particular host and/or not the code. It isn't hard to reproduce anyway:

**Steps to reproduce**:
1. Install WP 4 on a bog standard LAMP setup
2. Log in
3. Install Clef, keep all options default
   3.1. Not necessary to bother with setting up a user with Clef access
4. Log out
5. Go back to `/wp-login.php`
6. Click "login with a password"
   6.1. Observe LF being properly displayed
7. Click "Lost your password?"
8. You'll find the overlay and the hidden elements at `/wp-login.php?action=lostpassword`

Reproduced on PHP 5.4 with WP 4 and Clef 2.2.5.
Reproduced on PHP 5.5 with WP 4 and Clef 2.2.5.
Couldn't reproduce on PHP 5.4 with WP 3.9.2 and Clef 2.2.3. After upgrading to 2.2.5 (keeping WP at 3.9.2) reproduced the problem.
